_target_: src.models.unet_module.UNETLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  threshold: 0.0001
  patience: 5
  threshold_mode: "abs"

net:
  _target_: src.models.components.depth_net_efficient_ffn.DepthNet

# compile model for faster training with pytorch 2.0
compile: false
