_target_: src.models.unet_module.UNETLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 20

net:
  _target_: src.models.components.depth_net_efficient_ffn.DepthNet

# compile model for faster training with pytorch 2.0
compile: false
